# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from datetime import datetime
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QTableWidgetItem, QTableWidget, QDialog
from PyQt5.uic import loadUi

from .assistant_complexe_dialog import ComplexeDialog
from .fonction import *
from .constante import *
from .cheminpluscourt import *
from .tableur import *


class Complexe:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):

        self.dlgAProposDe = None
        self.iface = iface
        self.layer_rte_nommee = None
        self.layer = None

        self.ligne_selectionne = None
        self.selection = None

        self.dlg = None
        self.cheminpluscourt = None
        self.tableur = None

        # dictionnaire cotenant les liens vers route nommées
        self.dico_lien_route_nommee = {}

        # dictionnaire contenant les entités modifiées
        # clé : cleabs
        # valeur : (lien_vers AVANT, lien_vers APRES)
        self.dico_undo = {}

        # declaration et instanciation du QDialog aproposde sans generer de fichier .py correspondant au .ui (donc sans pyuic)
        self.dlgAProposDe = QDialog()
        loadUi(os.path.dirname(__file__) + "/aproposde.ui",self.dlgAProposDe)

    def affiche_log(self):
        afficherlog()

    def apropos(self):
        self.dlgAProposDe.show()

    def chemin_court(self):
        if len(self.selection) != 2:
            afficheerreur("Veuillez sélectionner 2 tronçons")
            return
        self.cheminpluscourt.cheminpluscourt()

        # activation du layer route
        project = QgsProject.instance()
        layer = project.mapLayersByName(LAYER_ESPACE_CO[0])
        self.iface.setActiveLayer(layer[0])
        self.layer = self.iface.activeLayer()


        # zoom sur la selection
        self.iface.actionZoomToSelected().trigger()

    def undo(self):
        # si le fichier de log est ouvert on quitte. il faut le fermer manuellement
        if not self.tableur.log_is_open():
            return
        self.dlg.pushButtonUndo.setEnabled(False)
        ligne_excel = []
        idlienvers = self.layer.fields().indexFromName(LIEN_VERS_RTE_NOMMEE)
        self.layer.startEditing()
        for cle,valeur in self.dico_undo.items():
            requete = QgsExpression(f"{CLEABS} = '{cle}'")
            iterateur = self.layer.getFeatures(QgsFeatureRequest(requete))
            ident = [i.id() for i in iterateur]

            self.layer.changeAttributeValue(ident[0],idlienvers,valeur[0])

            ligne_excel.append([datetime.today().strftime('%d %B %Y %H:%M'), "En cours de dévo",
                                cle,
                                valeur[1],
                                valeur[0]])

        self.layer.commitChanges()
        self.tableur.adddonnees(ligne_excel)
        self.tableur.sauvegarder()
        self.getconstituants_complexe()

    # si une ligne est sélectionnée
    def is_complexe_sel(self):
        pass

    def clic_check(self):
        if len(self.dico_lien_route_nommee) ==0:
            afficheerreur("Aucun complexe à fixer")
            self.dlg.checkBoxFixer.setChecked(False)
            return

        if not self.dlg.checkBoxFixer.isChecked():
            # reinitialisation des couleurs des lignes
            self.init_couleur_cellule(len(self.dico_lien_route_nommee))
            self.ligne_selectionne = None

        if self.ligne_selectionne is None and self.dlg.checkBoxFixer.isChecked():
            afficheerreur("Vous devez sélectionner un complexe avant de le fixer")
            self.dlg.checkBoxFixer.setChecked(False)

    def add_complexe(self):
        if self.layer.selectedFeatureCount() > 40:
            afficheerreur("Il n'est pas permis de modifier plus de 40 tronçons par transaction.\nAbandon")
            return

        if not self.dlg.checkBoxFixer.isChecked():
            afficheerreur("Vous devez sélectionner un complexe")
            return

        couple = self.get_cleabs_et_lien_route_nommee()
        # pas de selection
        # on a fixer le complexe, puis on a tout deselectionné
        # puis on a cliqué sur le complexe pour l'ajouter
        if couple[0] == "":
            return
        attr_cleabs_rte_nommee = couple[0]
        attr_lien_vers = couple[1]

        # si le lien est vide on ajoute simplement : attr_cleabs_rte_nommee
        if attr_lien_vers == "":
            attr_lien_vers = attr_cleabs_rte_nommee

        # si le lien n'est pas vide on test s'il existe deja et on concatene
        if attr_lien_vers != "":
            if attr_cleabs_rte_nommee in attr_lien_vers:
                pass
            else:
                attr_lien_vers += "/"
                attr_lien_vers += attr_cleabs_rte_nommee

        # modification sur la selection
        self.modifier_attribut(LIEN_VERS_RTE_NOMMEE,attr_lien_vers)


    def suppr_complexe(self):
        if self.layer.selectedFeatureCount() > 40:
            afficheerreur("Il n'est pas permis de modifier plus de 40 tronçons par transaction.\nAbandon")
            return

        if not self.dlg.checkBoxFixer.isChecked():
            afficheerreur("Vous devez sélectionner un complexe")
            return

        reponse = affichemessageAvertissement(f"Voulez vous vraiment retirer <b>{len(self.selection)}</b> tronçon(s) du complexe ?","Avertissement")
        if not reponse:
            return

        couple = self.get_cleabs_et_lien_route_nommee()
        # pas de selection
        # on a fixer le complexe, puis on a tout deselectionné
        # puis on a cliqué sur le complexe pour l'ajouter
        if couple[0] == "":
            return
        attr_cleabs_rte_nommee = couple[0]
        attr_lien_vers = couple[1]

        # si le lien n'est pas vide on test s'il existe deja et on concatene
        if attr_lien_vers != "":
            # le lien vert_rout n'est pas vide ET contient la cleabs à enlever
            if attr_cleabs_rte_nommee in attr_lien_vers:
                attr_lien_vers = attr_lien_vers.replace(attr_cleabs_rte_nommee,"")
                # si la cleabs etait en premier ou en dernier
                # il reste "/" en debut de chaine ou en fin de chaine , à supprimer
                if attr_lien_vers != "":
                    if attr_lien_vers[0] == "/":
                        attr_lien_vers = attr_lien_vers[1:]
                    # test si "/" en fin de chaine, a supprimer
                    if attr_lien_vers[-1] == "/":
                        attr_lien_vers = attr_lien_vers[:-1]
                    # si la chaine etait au milieu il y a un double "/" , 1 a supprimer (sans test)
                    attr_lien_vers = attr_lien_vers.replace("//","/")

            else:
                # lien_vers_rout... n'est pas vide mais ne contient pas la cleabs à supprimer
                pass

        # modification sur la selection
        self.modifier_attribut(LIEN_VERS_RTE_NOMMEE, attr_lien_vers)

    def get_cleabs_et_lien_route_nommee(self):

        list_complexes = list(self.dico_lien_route_nommee)
        complexe = list_complexes[self.ligne_selectionne]
        attr_cleabs_rte_nommee = complexe

        # on recupere les attributs du champs lien vers roite nommee...
        # pour ajouter ou concatener avec le caractere "/"
        # a faire : on peut selectionner plusieurs troncons
        self.set_active_layer(LAYER_ESPACE_CO[0])
        list_sel_layer_rte = self.layer.selectedFeatures()
        if len(list_sel_layer_rte) == 0:
            return "",""
        idchamps = self.layer.fields().indexFromName(LIEN_VERS_RTE_NOMMEE)
        attr = list_sel_layer_rte[0].attributes()
        attr_lien_vers = attr[idchamps]

        return attr_cleabs_rte_nommee,attr_lien_vers

    def modifier_attribut(self,champs,valeur):

        self.dlg.pushButtonUndo.setEnabled(True)

        # si le fichier de log est ouvert on quitte. il faut le fermer manuellement
        if not self.tableur.log_is_open():
            return
        ligne_excel = []

        idchamps = self.layer.fields().indexFromName(champs)
        idcleabs = self.layer.fields().indexFromName(CLEABS)
        idlienvers = self.layer.fields().indexFromName(LIEN_VERS_RTE_NOMMEE)
        self.layer = self.iface.activeLayer()
        selection = self.layer.selectedFeatures()

        self.dico_undo.clear()

        # remplacer les occurences de "NULL" en "" sur la variable valeur.
        # sinon plantage du modele
        valeur_sans_NULL = valeur.replace("NULL/","")

        self.layer.startEditing()
        for sel in selection:
            attr = sel.attributes()
            # if attr[idlienvers] == "NULL":
            #     valeur = ""
            if attr[idlienvers] != valeur_sans_NULL:
                ligne_excel.append([datetime.today().strftime('%d %B %Y %H:%M'), "En cours de dévo",
                                    attr[idcleabs],
                                    attr[idlienvers],
                                    valeur_sans_NULL])

                self.layer.changeAttributeValue(sel.id(), idchamps,valeur_sans_NULL)
                # initialiser un dictionnaire pour le undo
                self.dico_undo[attr[idcleabs]] = (attr[idlienvers], valeur_sans_NULL)

        self.layer.commitChanges()

        self.tableur.adddonnees(ligne_excel)
        self.tableur.sauvegarder()
        self.dlg.pushButtonLog.setEnabled(True)
        self.dlg.pushButtonSelConstituants.setEnabled(True)

    # selectionne tous les troncons du complexe choisi dans la tablewidget
    # par le bouton : pushButtonSelConstituants
    def getconstituants_complexe(self):
        # astuce : depuis python 3.7 les dictionnaires restent ordonnés suivant l'ordre d'insertion
        # -> convertir le dictionnaire en list et on accéde a l'element qui correspond à la ligne du
        # tablewidget
        # je ne fais pas : list(self.dico_lien_route_nommee.items()
        # pas besoin, je veux juste les clées --> cleabs

        if not self.dlg.checkBoxFixer.isChecked():
            afficheerreur("Vous devez sélectionner un complexe")
            return



        list_complexes = list(self.dico_lien_route_nommee)
        complexe = list_complexes[self.ligne_selectionne]

        # il faut sélectionner les troncon sur la couche route dont lien_vers..
        # contient la cleabs de la route nommee du dictionnaire
        expr = f"{LIEN_VERS_RTE_NOMMEE} LIKE '%{complexe}%'"

        self.set_active_layer(LAYER_ESPACE_CO[0])
        self.layer.removeSelection()
        self.layer.selectByExpression(expr, QgsVectorLayer.AddToSelection)

    # rempli la tablewidget avec la liste des complexes du troncon
    def Add_complexe_in_tablewidget(self):
        if self.layer.selectedFeatureCount() != 1:
            return

        if len(self.dico_lien_route_nommee) == 0:
            self.dlg.pushButtonRetirer.setEnabled(False)
            self.dlg.pushButtonAjouter.setEnabled(False)
            self.dlg.pushButtonSelConstituants.setEnabled(False)
        else :
            self.dlg.pushButtonRetirer.setEnabled(True)
            self.dlg.pushButtonAjouter.setEnabled(True)
            self.dlg.pushButtonSelConstituants.setEnabled(True)

        self.dlg.tableWidget.setRowCount(len(self.dico_lien_route_nommee))

        compt = 0
        for cle,attribut in self.dico_lien_route_nommee.items():
            self.dlg.tableWidget.setItem(compt, 0, QTableWidgetItem(attribut[0]))
            self.dlg.tableWidget.setItem(compt, 1, QTableWidgetItem(attribut[1]))
            self.dlg.tableWidget.setItem(compt, 2, QTableWidgetItem(attribut[2]))
            self.dlg.tableWidget.setItem(compt, 3, QTableWidgetItem(attribut[3]))
            # taille des lignes (on peut pas plus petit que le contenant
            self.dlg.tableWidget.setRowHeight(compt, 1)
            compt +=1

        # mettre toute sles ligne en blanc
        self.init_couleur_cellule(len(self.dico_lien_route_nommee))

    def clic_in_celulle(self,ligne):

        self.ligne_selectionne = ligne
        self.dlg.checkBoxFixer.setChecked(True)
        self.dlg.pushButtonSelConstituants.setEnabled(True)
        self.dlg.pushButtonAjouter.setEnabled(True)
        self.dlg.pushButtonRetirer.setEnabled(True)


        # colorier la ligne apres avoir reinitialiser (couleur) toutes les cellules
        self.init_couleur_cellule(len(self.dico_lien_route_nommee))
        for col in range(0,len(LIST_AUTRE_CHAMPS)):
            item = self.dlg.tableWidget.item(ligne, col)
            item.setBackground(QColor(255, 255, 80))

    def init_couleur_cellule(self,nb_ligne):
        for ligne in range(0,nb_ligne):
            for colonne in range(0,len(LIST_AUTRE_CHAMPS)):
                item = self.dlg.tableWidget.item(ligne, colonne)
                # # item = self.dlg.tableWidget.item(1, 1)
                # initvouleur est appelé aussi avant l'affichage du dial, donc try pour le cas là
                try:
                    item.setBackground(QColor(220, 220, 220))
                except AttributeError:
                    pass

    def set_dico_lien_route_nommee(self):
        self.dico_lien_route_nommee.clear()
        # si nb selection different de 1 on fait rien
        if len(self.selection) != 1:
            self.dlg.tableWidget.setRowCount(0)
            return
        # recuperation des cleabs du champs lien vers route nommee
        fields = self.layer.fields()
        liste_cleabs = []
        for field in fields:
            field_value = self.selection[0][field.name()]

            if field.name() == LIEN_VERS_RTE_NOMMEE:
                liste_cleabs = field_value.split("/")

        # si la liste contient que des element vide ou "NULL
        if all(element == "" or element == "NULL" for element in liste_cleabs):
            return


        # recuperation des attributs de la route nommee corrspondant aux cleabs ci dessus
        # sur le layer route_numerotee_ou_nommee
        project = QgsProject.instance()
        layer = project.mapLayersByName(LAYER_ESPACE_CO[1])

        type_route = ""
        gestionnaire = ""
        numero = ""
        toponyme = ""
        for valeur_champs in liste_cleabs:
            requete = QgsFeatureRequest().setFilterExpression(f'"{CLEABS}" = \'{valeur_champs}\'')
            for feature in layer[0].getFeatures(requete):
                for field in layer[0].fields():
                    if field.name() == LIST_AUTRE_CHAMPS[0]:
                        type_route = feature[field.name()]
                    if field.name() == LIST_AUTRE_CHAMPS[1]:
                        gestionnaire = feature[field.name()]
                    if field.name() == LIST_AUTRE_CHAMPS[2]:
                        numero = feature[field.name()]
                    if field.name() == LIST_AUTRE_CHAMPS[3]:
                        toponyme = feature[field.name()]
            self.dico_lien_route_nommee[valeur_champs] = (type_route,gestionnaire,numero,toponyme)

    def actualiserSelection(self):

        # print("actualisersel : ",self.layer.name())
        nbsel = self.layer.selectedFeatureCount()
        if nbsel > 40:
            self.dlg.label_nbselection.setText(f"<span style='color: red'><b>Vous avez "
                                               f"sélectionné plus de 40 tronçons ({nbsel})</b></span>")
        else:
            self.dlg.label_nbselection.setText(f"<span style='color: red'><b>{nbsel}</b></span> entité(s) sélectionnée(s)")

        # if not self.dlg.isVisible():
        #     return


        # gestion de la couleur de selection
        couleur = self.dlg.mColorButton.color()
        self.iface.mapCanvas().setSelectionColor(couleur)
        
        self.selection = self.layer.selectedFeatures()

        if self.layer.selectedFeatureCount()==0:
            self.dlg.pushButtonRetirer.setEnabled(False)
            self.dlg.pushButtonAjouter.setEnabled(False)
            self.dlg.pushButtonSelConstituants.setEnabled(False)
        else:
            self.dlg.pushButtonRetirer.setEnabled(True)
            self.dlg.pushButtonAjouter.setEnabled(True)
            self.dlg.pushButtonSelConstituants.setEnabled(True)


        if not self.dlg.checkBoxFixer.isChecked():
            self.set_dico_lien_route_nommee()
            self.Add_complexe_in_tablewidget()

    def personnaliser_qtablewidget(self):
        # Interdire l'édition des cellules
        self.dlg.tableWidget.setEditTriggers(QTableWidget.NoEditTriggers)
        self.dlg.tableWidget.setColumnCount(4)
        self.dlg.tableWidget.setHorizontalHeaderLabels([LIST_AUTRE_CHAMPS[0], LIST_AUTRE_CHAMPS[1],LIST_AUTRE_CHAMPS[2],LIST_AUTRE_CHAMPS[3]])
        self.dlg.tableWidget.setColumnWidth(0, 120)
        self.dlg.tableWidget.setColumnWidth(1, 85)
        self.dlg.tableWidget.setColumnWidth(2, 50)
        self.dlg.tableWidget.setColumnWidth(3, 150)

        self.dlg.tableWidget.setSelectionBehavior(QTableWidget.SelectRows)
        self.dlg.tableWidget.setSelectionMode(QTableWidget.NoSelection)
        entete = self.dlg.tableWidget.horizontalHeader()
        entete.setStyleSheet("color: #db1515 ;font-weight: bold")

    def set_active_layer(self,layer):
        # project = QgsProject.instance()
        # layer = project.mapLayersByName(layer)
        # self.iface.setActiveLayer(layer[0])
        # self.layer = self.iface.activeLayer()
        project = QgsProject.instance()
        layer = project.mapLayersByName(LAYER_ESPACE_CO[0])
        if not layer:
            afficheerreur(f"la couche \"{LAYER_ESPACE_CO[0]}\" n'existe pas", "assistant complexe")
            return False
        else:
            self.iface.setActiveLayer(layer[0])
            self.layer = self.iface.activeLayer()
            return True


    def islayer_espaceco(self):
        project = QgsProject.instance()
        text = f"Une ou plusieurs couches suivantes ne sont pas accessibles :<br>"
        isok = True
        for layer_espace_co in LAYER_ESPACE_CO:
            layer = project.mapLayersByName(layer_espace_co)
            if not layer:
                text += f"<b>{layer_espace_co}</b><br>"
                isok = False
        if not isok:
            QMessageBox.warning(None,"Avertissement",text)
            return False
        else:
            return True

    def colorchange(self):
        self.actualiserSelection()

    def initGui(self):
        pass

    def unload(self):
        pass


    def run(self):
        # Create the dialog with elements  and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        # print(self.first_start)
        # if self.first_start:
        #     self.first_start = False

        self.dlg = ComplexeDialog()
        self.dlg.setWindowTitle(TITRE)

        # self.layer = self.iface.activeLayer()
        # TODO a verifier
        project = QgsProject.instance()
        layer = project.mapLayersByName(LAYER_ESPACE_CO[0])
        if not layer:
            afficheerreur(f"la couche \"{LAYER_ESPACE_CO[0]}\" n'existe pas", "Assistant complexe")
            return
        else:
            self.iface.setActiveLayer(layer[0])
            self.layer = self.iface.activeLayer()


        self.dlgAProposDe.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)
        self.dlgAProposDe.setWindowTitle(TITRE)

        # gestion couleur de la sélection
        self.dlg.mColorButton.setColor(self.iface.mapCanvas().selectionColor())
        self.dlg.mColorButton.colorChanged.connect(self.colorchange)

        # instanciation de la class dhemin le plus court
        self.cheminpluscourt = cheminpluscourt(self.iface, self.layer)

        # instanciation du tableur pour le log
        self.tableur = Tableur()

        # est ce que les layer de l'espace co sont disponibles
        if not self.islayer_espaceco():
            return

        # definition d'un layer route numerotee ou nommee
        project = QgsProject.instance()
        layer  = project.mapLayersByName(LAYER_ESPACE_CO[1])
        self.layer_rte_nommee = layer[0]


        # "fixer" est coché par defaut
        # self.dlg.checkBoxFixer.setChecked(False)
        self.dlg.label_check.setStyleSheet("font-weight: bold")

        # personnaliser l'aspect du tablewidget
        self.personnaliser_qtablewidget()

        # evenement clic dans une celulle
        self.dlg.tableWidget.cellClicked.connect(self.clic_in_celulle)

        # evenement des boutons
        self.dlg.pushButtonSelConstituants.clicked.connect(self.getconstituants_complexe)
        self.dlg.pushButtonRetirer.clicked.connect(self.suppr_complexe)
        self.dlg.pushButtonAjouter.clicked.connect(self.add_complexe)
        self.dlg.pushButtonLog.clicked.connect(self.affiche_log)
        self.dlg.pushButtonUndo.clicked.connect(self.undo)
        self.dlg.pushButtonUndo.setEnabled(False)
        self.dlg.pushButtonCheminCourt.clicked.connect(self.chemin_court)
        self.dlg.pushButtonAPropos.clicked.connect(self.apropos)
        self.dlg.checkBoxFixer.clicked.connect(self.clic_check)

        # si le mog existe on active le bouton*
        fic = os.path.dirname(__file__) + "/transaction.xlsx"
        self.dlg.pushButtonLog.setEnabled(os.path.isfile(fic))


        # peronnalisation des boutons
        self.dlg.pushButtonSelConstituants.setStyleSheet("background-color: #30b300 ;font-weight: bold")
        self.dlg.pushButtonRetirer.setStyleSheet("background-color: #30b300 ;font-weight: bold")
        self.dlg.pushButtonAjouter.setStyleSheet("background-color: #30b300 ;font-weight: bold")

        # evenement selection change
        self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)
        self.actualiserSelection()

        self.dlg.setWindowFlags(Qt.WindowStaysOnTopHint)
        # # show the dialog
        self.dlg.show()
        self.Add_complexe_in_tablewidget()


        # Run the dialog event loop
        # result = self.dlg.exec_()
        # See if OK was pressed
        # if result == 0:
        #     print("fermeture")

        # if result:
        #     # Do something useful here - delete the line containing pass and
        #     # substitute with your code.
        #     pass
